services:
  api:
    image: ghcr.io/ahendest/cs-project-api:latest   # or a tagged release like :1.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=sqldata,1433;Database=csproject;User ID=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      AllowedOrigins__0: ${CORS_ORIGINS}
    ports:
      - "8080:8080"
    depends_on:
      sqldata:
        condition: service_healthy

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: csproject-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost,1433", "-U", "sa", "-P", "${SA_PASSWORD}", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
