apiVersion: v1
kind: Secret
metadata:
  name: api-conn
  labels:
    app: cs-project-api
type: Opaque
stringData:
  DefaultConnection: "Server=sqldata,1433;Database=csproject;User ID=csapp;Password=${CSAPP_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true"
