apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-project-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cs-project-api
  template:
    metadata:
      labels:
        app: cs-project-api
    spec:
      containers:
      - name: cs-project-api
        image: ghcr.io/ahendest/cs-project-api
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
  
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: api-conn
              key: DefaultConnection
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: Jwt__Key
        - name: Jwt__Issuer
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: Jwt__Issuer
        - name: Jwt__Audience
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: Jwt__Audience
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: cs-project-api-service
spec:
  selector:
    app: cs-project-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer   # keep; we'll use port-forward on kind
