// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class AuditLog
{
    public long Id { get; set; }

    public string TableName { get; set; }

    public long RecordId { get; set; }

    public string Operation { get; set; }

    public string OldValues { get; set; }

    public string NewValues { get; set; }

    public long ModifiedBy { get; set; }

    public DateTimeOffset ModifiedAt { get; set; }

    public Guid CorrelationId { get; set; }
}