// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class CorrectionLog
{
    public int Id { get; set; }

    public string TargetTable { get; set; }

    public int TargetId { get; set; }

    public int Type { get; set; }

    public string Reason { get; set; }

    public int RequestedById { get; set; }

    public int? ApprovedById { get; set; }

    public DateTime RequestedAtUtc { get; set; }

    public DateTime? ApprovedAtUtc { get; set; }

    public Guid AuditCorrelationId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Employee ApprovedBy { get; set; }

    public virtual Employee RequestedBy { get; set; }
}