// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class CustomerTransaction
{
    public int Id { get; set; }

    public int PumpId { get; set; }

    public int StationFuelPriceId { get; set; }

    public decimal Liters { get; set; }

    public decimal PricePerLiter { get; set; }

    public decimal TotalPrice { get; set; }

    public DateTimeOffset TimestampUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<CustomerPayment> CustomerPayments { get; set; } = new List<CustomerPayment>();

    public virtual Pump Pump { get; set; }

    public virtual StationFuelPrice StationFuelPrice { get; set; }
}