// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class CustomerPayment
{
    public int Id { get; set; }

    public int CustomerTransactionId { get; set; }

    public int Method { get; set; }

    public decimal Amount { get; set; }

    public string AuthorizationCode { get; set; }

    public DateTime ProcessedAtUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual CustomerTransaction CustomerTransaction { get; set; }
}