// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class Employee
{
    public int Id { get; set; }

    public int? StationId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int Role { get; set; }

    public DateTime HireDateUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<CorrectionLog> CorrectionLogApprovedBies { get; set; } = new List<CorrectionLog>();

    public virtual ICollection<CorrectionLog> CorrectionLogRequestedBies { get; set; } = new List<CorrectionLog>();

    public virtual ICollection<ShiftEmployee> ShiftEmployees { get; set; } = new List<ShiftEmployee>();

    public virtual Station Station { get; set; }
}