// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class ExchangeRate
{
    public int Id { get; set; }

    public string BaseCurrency { get; set; }

    public string QuoteCurrency { get; set; }

    public decimal Rate { get; set; }

    public DateTime RetrievedAtUtc { get; set; }

    public string Source { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }
}