// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class PricePolicy
{
    public int Id { get; set; }

    public int? StationId { get; set; }

    public int FuelType { get; set; }

    public int Method { get; set; }

    public decimal? BaseUsdPrice { get; set; }

    public decimal? MarginPct { get; set; }

    public decimal? MarginRon { get; set; }

    public decimal RoundingIncrement { get; set; }

    public int RoundingMode { get; set; }

    public DateTime EffectiveFromUtc { get; set; }

    public DateTime? EffectiveToUtc { get; set; }

    public int Priority { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Station Station { get; set; }

    public virtual ICollection<StationFuelPrice> StationFuelPrices { get; set; } = new List<StationFuelPrice>();
}