// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class ShiftEmployee
{
    public int Id { get; set; }

    public int ShiftId { get; set; }

    public int EmployeeId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Shift Shift { get; set; }
}