// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class StationFuelPrice
{
    public int Id { get; set; }

    public int StationId { get; set; }

    public int FuelType { get; set; }

    public decimal PriceRon { get; set; }

    public DateTime EffectiveFromUtc { get; set; }

    public DateTime? EffectiveToUtc { get; set; }

    public int? DerivedFromPolicyId { get; set; }

    public decimal? FxRateUsed { get; set; }

    public decimal? CostRonUsed { get; set; }

    public string Reason { get; set; }

    public int? CreatedByEmployeeId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<CustomerTransaction> CustomerTransactions { get; set; } = new List<CustomerTransaction>();

    public virtual PricePolicy DerivedFromPolicy { get; set; }

    public virtual Station Station { get; set; }
}