// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class Station
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<PricePolicy> PricePolicies { get; set; } = new List<PricePolicy>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual ICollection<StationFuelPrice> StationFuelPrices { get; set; } = new List<StationFuelPrice>();

    public virtual ICollection<SupplierInvoice> SupplierInvoiceStationId1Navigations { get; set; } = new List<SupplierInvoice>();

    public virtual ICollection<SupplierInvoice> SupplierInvoiceStations { get; set; } = new List<SupplierInvoice>();

    public virtual ICollection<Tank> Tanks { get; set; } = new List<Tank>();
}