// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class SupplierInvoice
{
    public int Id { get; set; }

    public int SupplierId { get; set; }

    public int StationId { get; set; }

    public DateTime DeliveryDateUtc { get; set; }

    public string Currency { get; set; }

    public decimal FxToRon { get; set; }

    public int? StationId1 { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Station Station { get; set; }

    public virtual Station StationId1Navigation { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual ICollection<SupplierInvoiceLine> SupplierInvoiceLines { get; set; } = new List<SupplierInvoiceLine>();

    public virtual ICollection<SupplierPaymentApply> SupplierPaymentApplies { get; set; } = new List<SupplierPaymentApply>();
}