// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class SupplierPaymentApply
{
    public int Id { get; set; }

    public int SupplierPaymentId { get; set; }

    public int SupplierInvoiceId { get; set; }

    public decimal AppliedAmount { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual SupplierInvoice SupplierInvoice { get; set; }

    public virtual SupplierPayment SupplierPayment { get; set; }
}