// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cs_project.Infrastructure.Models;

public partial class Tank
{
    public int Id { get; set; }

    public int StationId { get; set; }

    public int FuelType { get; set; }

    public decimal CapacityLiters { get; set; }

    public decimal CurrentVolumeLiters { get; set; }

    public DateTime? LastRefilledAtUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<Pump> Pumps { get; set; } = new List<Pump>();

    public virtual Station Station { get; set; }

    public virtual ICollection<SupplierInvoiceLine> SupplierInvoiceLines { get; set; } = new List<SupplierInvoiceLine>();
}